# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd code/ && npm install -g webpack webpack-cli --save-dev
    cd code/ && npm install
    cd code/ && npm run build
    cd code/ && npx webpack --config webpack.config.js
  displayName: 'npm install, run webpack'
